# Generated by Django 2.2 on 2020-08-04 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200804_0756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
